# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 00:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('tag', models.CharField(db_index=True, max_length=14)),
                ('additional_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('additional_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('time_difficulty', models.PositiveSmallIntegerField(choices=[(1, '<1 Hour'), (2, '1-2 Hours'), (3, '2-4 Hours'), (4, '4-8 Hours'), (5, '8+ Hours')], default=1)),
                ('energy_difficulty', models.PositiveSmallIntegerField(choices=[(1, 'No Energy at all'), (2, 'Little Energy'), (3, 'Moderate Energy'), (4, 'Heavy Energy'), (5, 'All-Consuming Energy')], default=2)),
                ('focus_difficulty', models.PositiveSmallIntegerField(choices=[(1, 'No Attention at all'), (2, 'Little Attention'), (3, 'Concentration'), (4, 'Focused Concentration'), (5, 'Complete Concentration')], default=3)),
                ('completed_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('goals', models.ManyToManyField(to='api.Goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'Backlog'), (1, 'Prioritized'), (2, 'In Progress'), (3, 'Paused'), (4, 'Completed'), (5, 'Discarded')], default=1)),
                ('initiated', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.Task')),
            ],
            options={
                'ordering': ['-initiated'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together=set([('user', 'tag')]),
        ),
    ]
